### ISSUE TITLE
Add support for retina tiles

### ISSUE THREAD

**Issue by bcherny** [openstreetmap/mod_tile#110]
Currently, maps look very bad on retina:
<img width="376" alt="screen shot 2015-09-10 at 11 20 31 am" src="https://cloud.githubusercontent.com/assets/1761758/9797024/fa60861e-57ad-11e5-98a9-90a1cf41ce43.png">

For reference, here's the same loction rendered via Google Maps:
<img width="367" alt="screen shot 2015-09-10 at 11 38 32 am" src="https://cloud.githubusercontent.com/assets/1761758/9797553/9d372b84-57b0-11e5-8b9e-8baa4012afc3.png">

I can't find any data online, but it seems to me that a large portion of devices (phones, tablets, computers) have retina screens. Open street maps underperforms google maps on these devices, almost to the point of being unusable.

Also see https://github.com/openstreetmap/openstreetmap-website/issues/104

**Comment by pnorman** [comment]
#82 added retina support in 2014.

**Comment by bcherny** [comment]
Is the issue that the osm website isn't requesting retina tiles?

**Comment by apmon** [comment]
The software stack itself does support retina tiles, and so if you set up your own tile server, you could create them. However, osm.org has for operational reasons decided not to support retina tiles so far. Retina tiles both need considerably more bandwidth to server the tiles, as well disk space to store them. Both are at  a premium and so far it has not been worth it to offer them. I don't know if that will change anytime soon. That is up to the operations team to decide if they can "afford" the additional resources required.

**Comment by jburgess777** [comment]
I agree with @apmon. The OSM servers are unlikely to ever offer the same tiles in multiple resolutions because this takes more resources. The more likely, longer term, solution is to use vector tiles where the client renders the data and is resolution independent. Vector tiles provide other benefits, for example the client can choose which language use for name tags and render the data differently depending on the use case (e.g. selectively showing or hiding different elements of the map depending on what is important to the user).

**Comment by apmon** [comment]
I am not sure it would be necessary to store the tiles at multiple resolutions. Instead one could always deliver the high resolution tiles and those devices that don't have high DPI displays would just display the tiles at %50 rather than %100.

But a) Is it even feasible to store the tiles at high DPI once, and b) that would then increase the network bandwidth for serving tiles even when the device is low DPI.

So that solution would only be feasible once the majority of devices are high DPI.

Do we have any statistics of what type of device and their DPI access the tiles on osm.org?

**Comment by bcherny** [comment]
Vector tiles would be interesting. They're resolution independent (ie. Future proof), will likely offer bandwidth savings over png tiles, and will allow the client to not only show/hide elements on demand, but control every aspect of styling with CSS.

**Comment by johsin18** [comment]
This discussion is 2,5 years old now, I would like to propose reconsidering the decision made. 

More and more devices are getting high DPI screens (in particular, all new mobile devices have such a display). Vector tiles have still not landed, and even Google Maps falls back (lite version) to raster tiles for mobile devices, apparently for performance reasons.

For the layers Cycle Map and Transport Map, retina tiles are already served (apparently by Thunderforest, though).

Hasn't the cost for CPU, storage and bandwidth declined in the meantime, so that we could afford Retina tiles now?

**Comment by xamanu** [comment]
Please move this discussion to the [OpenStreetMap.org server configuration](https://github.com/openstreetmap/chef/blob/master/cookbooks/tile/templates/default/renderd.conf.erb) `mod_tile` has support for it.
