### ISSUE TITLE
Configure mod_tile cache for serving only existing metatiles

### ISSUE THREAD

**Issue by tierpod** [openstreetmap/mod_tile#119]
Hello. Is there any way to configure mod_tile for serving only existing prerendering metatiles? I want to realize the following scheme. I have 2 servers:

1. First with postgres + mod_tile + renderd services. I run script to render all needed tiles. mod_tile create cache of all needed tiles to /var/lib/mod_tile/ metatiles.
2. I copy this cache to second server.
3. Second server with apache + mod_tile should show files from /var/lib/mod_tile metatiles and should never render them again.

I think that I must setup some cache setting in mod_tile.conf

I previously tried to use nginx for file caching z/x/y.png tiles, but it has a huge size of files.

**Comment by woodpeck** [comment]
Please do not abuse github tickets as a discussion/help forum. Use the tile-serving@openstreetmap.org mailing list instead, or ask on help.openstreetmap.org.

To solve your issue, you could simply choose not to run renderd on the second server, and create a planet-import-complete file with a timestamp far in the past. 

If you want to set up a tile cache then don't use nginx but squid; it has a mode where it will save all cached entities to one large file in the file system rather than tons of small files. This will improve performance when used as a tile cache.

**Comment by tierpod** [comment]
Sorry and thank you!
