### ISSUE TITLE
How to never have tiles expiring? 

### ISSUE THREAD

**Issue by damiendevienne** [openstreetmap/mod_tile#121]
Hello, 
Is there a simple way to tell mod_tile to never re-render tiles? I want my tiles to be rendered the first time but then to stay  stored forever. Is this possible? 
Thanks a lot, 
D

**Comment by woodpeck** [comment]
Please do not abuse GitHub tickets for Q&A. They are meant for bug reports or improvements. If you have questions, go to help.openstreetmap.org or the [tile serving mailing list](http://lists.openstreetmap.org/listinfo/tile-serving). 

The solution for your problem is to place a file named planet-import-complete in the /var/lib/mod_tile directory and make sure that this file has a timestamp earlier than the earliest tile (use the `touch` utility to set the timestamp to 1980 or so). This will make mod_tile think that the last data import is that long ago, and that hence the re-rendering of tiles makes no sense.

**Comment by damiendevienne** [comment]
OK, very sorry for the spam, I didn't know where to ask... And thanks for the answer. 
Best,
