### ISSUE TITLE
Segmentation fault on a command "sudo -u taras renderd -f -c /usr/local/etc/renderd.conf"

### ISSUE THREAD

**Issue by dubravat** [openstreetmap/mod_tile#165]
Good afternoon dear all.

I definitely need your help because I am new to Apache technologies and renderd and do not know how to overcome current problem.

Could you be so kind to inspect my code and assist me to find the solution. I will greatly appreciate that.

I am following stages written in a manual: [switch2osm_16-04-2-lts](https://switch2osm.org/manually-building-a-tile-server-16-04-2-lts/)

But on a stage of "Running renderd for the first time" I got problems.
When I execute next command `sudo -u taras renderd -f -c /usr/local/etc/renderd.conf`
I received next reply in my Terminal:
```
renderd[24791]: Rendering daemon started
renderd[24791]: Initiating reqyest_queue
renderd[24791]: Parsing section renderd
renderd[24791]: Parsing render section 0
renderd[24791]: Parsing section mapnik
renderd[24791]: Parsing section ajt
renderd[24791]: config renderd: unix socketname=/var/run/renderd/renderd.sock
renderd[24791]: config renderd: num_threads=2
renderd[24791]: config renderd: num_slaves=0
renderd[24791]: config renderd: tile_dir=/var/lib/mod_tile
renderd[24791]: config renderd: stats_file=/var/run/renderd/renderd.stats
renderd[24791]: config mapnik:  plugins_dir=/usr/lib/mapnik/3.0/input
renderd[24791]: config mapnik:  font_dir=/usr/share/fonts/truetype
renderd[24791]: config mapnik:  font_dir_recurse=1
renderd[24791]: config renderd(0): Active
renderd[24791]: config renderd(0): unix socketname=/var/run/renderd/renderd.sock
renderd[24791]: config renderd(0): num_threads=2
renderd[24791]: config renderd(0): tile_dir=/var/lib/mod_tile
renderd[24791]: config renderd(0): stats_file=/var/run/renderd/renderd.stats
renderd[24791]: config map 0:   name(ajt) file(/home/taras/Documents/projects/luxembourg/src/openstreetmap-carto/mapnik.xml) uri(/hot/) htcp() host(localhost)
renderd[24791]: Initialising unix server socket on /var/run/renderd/renderd.sock
renderd[24791]: Created server socket 5
renderd[24791]: Renderd is using mapnik version 2.2.0
renderd[24791]: DEBUG: Loading font: /usr/share/fonts/truetype/lohit-punjabi/Lohit-Punjabi.ttf
... (some very similar code with no errors)
renderd[24791]: DEBUG: Loading font: /usr/share/fonts/truetype/tlwg/TlwgTypewriter-Bold.ttf
renderd[24791]: DEBUG: Loading font: /usr/share/fonts/truetype/tlwg/Purisa.ttf
renderd[24791]: DEBUG: Loading font: /usr/share/fonts/truetype/olga/GFSOlga.otf
Running in foreground mode...
renderd[24791]: Starting stats thread
debug: init_storage_backend: initialising file storage backend at: /var/lib/mod_tile
debug: init_storage_backend: initialising file storage backend at: /var/lib/mod_tile
renderd[24791]: Loading parameterization function for 
renderd[24791]: Loading parameterization function for 
**Segmentation fault**
```

What does it mean Segmentation fault and what should I do?

Also, when I open my browser [http://130.89.234.165/mod_tile/0/0/0.png](http://130.89.234.165/mod_tile/0/0/0.png) I got next reply on the black background:
`The image “http://130.89.234.165/mod_tile/0/0/0.png” cannot be displayed, because it contains errors.`
Thank you fellows.

**Comment by SomeoneElseOSM** [comment]
It's unlikely to be related this map style, to be honest.  It's a more appropriate question for the OSM help site https://help.openstreetmap.org/questions/ .  Stackoverflow (as usual) has a description of what a Segmentation Fault is https://stackoverflow.com/questions/2346806/what-is-a-segmentation-fault , and there have been people with similar problems before https://duckduckgo.com/html?q=%22renderd%22%20%22segmentation%20fault%22 (though I've not seen it myself).  When you ask the question at the help site make sure you specify where (if at all) you deviated rom the switch2osm instructions, and stuff like what OS and version you're using, if it's different to what's specified.

The problem might be that the latest release of the map style requires changes to the switch2osm guide (which wouldn't be a problem with the map style since that guide is supposed to work with the latest version), or that there's upstream stuff needs merging into the renderd/mod_tile that that guide uses (that's certainly true for Ubuntu 17 support, for example).
