### ISSUE TITLE
How to reload style.xml?

### ISSUE THREAD

**Issue by OnkelTem** [openstreetmap/mod_tile#171]
When I change `style.xml` (e.g recompile using `carto`) how to reload the file? I don't see any activity in the logs when I update `style.xml` file.

**Comment by SomeoneElseOSM** [comment]
I normally do:

    /etc/init.d/renderd restart
    /etc/init.d/apache2 restart

If you do want to see metatiles from the previous style, delete those as well.  Shift-refresh the browser so that that isn't caching anything either.

**Comment by OnkelTem** [comment]
@SomeoneElseOSM Ah, thanks, I see. I thought there is some mode which I missed in the docs - like watching updates of the styles. But I understand - it's not for styles developing but for tiles serving.

**Comment by SomeoneElseOSM** [comment]
Well wrappers for the "carto" compiler such as Kosmtik might do things like that, but as I'm usually reloading a database because of lua changes (which is not the case with this style) I tend to do something like https://github.com/SomeoneElseOSM/SomeoneElse-style/blob/master/update_render.sh or https://github.com/SomeoneElseOSM/SomeoneElse-style-legend/blob/master/update_generated_legend.sh .  You might not want to do everything in those, but some of what's in there might be useful.

**Comment by OnkelTem** [comment]
Thank you!
