### ISSUE TITLE
Disable writing to syslog / performance improvement?

### ISSUE THREAD

**Issue by EnemyArea** [openstreetmap/mod_tile#185]
Hey guys, is there any way to disable the writing to syslog? I think it would be a huge performance boost if it dont do it.

**Comment by woodpeck** [comment]
I cannot see any syslog activity except in debug mode when submitting a rendering request. Given that a rendering request will generally result in hundreds of SQL queries on the backend, I would be very surprised to see a "huge" performance boost by dropping a syslog call, especially if all you need to do is set log level to something lesser than DEBUG to avoid it?

**Comment by EnemyArea** [comment]
Hello, how I set the log level lesser than debug  :) ?

**Comment by OsamaShabrez** [comment]
Change log level in /etc/syslog.conf

**Comment by it-solutions-zehaczek** [comment]
Sorry but this is not solved. I also like to get rid of all these DEBUG enries in syslog in production. Is there no logging option in `/etc/renderd.conf` or apache site, like `ModTileLogLevel` or something?

**Comment by SomeoneElseOSM** [comment]
@it-solutions-zehaczek It "works for me", in that whenever I set up a server I have to remember to turn the logging on, otherwise I get confused when I see no log entries!  What exactly are you doing and in what order, and with what software version on what OS?  

For the avoidance of doubt, if you follow https://switch2osm.org/serving-tiles/manually-building-a-tile-server-ubuntu-22-04-lts/ you will get debug logging info because those instructions deliberately tell people to turn it on, but that's to help people setting up their first tile server to see what is going on.

**Comment by it-solutions-zehaczek** [comment]
I am using Debian 11 (Bullseye) and their packaged renderd. I didn't turn on any logging explicitely. I can see in the linked Ubuntu page `Environment=G_MESSAGES_DEBUG=all` is set in the systemd script. I may use that in my debian systemd script. What is the appropiate value instead of `all` to turn off logging?

**Comment by SomeoneElseOSM** [comment]
> I am using Debian 11 (Bullseye) and their packaged renderd. I didn't turn on any logging explicitely

I'm sure that Noah would be very happy with your choice of operating system :)

That has a very old renderd in it (from 2020) that predates turning debug off (in 2021).  You'll notice that https://switch2osm.org/serving-tiles/manually-building-a-tile-server-debian-11/ (which also dates from 2020) doesn't explicitly say "turn debug back on", which the Ubuntu 22.04 page does.

https://packages.debian.org/stable/libapache2-mod-tile (0.5-2)
https://packages.ubuntu.com/jammy/libapache2-mod-tile (0.6.1-1)

The good news is that (every time I've tried it recently) building mod_tile from source "just works".  See https://github.com/openstreetmap/mod_tile/blob/master/docs/build/building_on_ubuntu_20_04.md .  Those instructions work on Ubuntu 22.04 and surely also will on the half-way-house of Debian 11.

(unrelated to mod_tile / renderd, but) other issues that you'll find with the Debian 11 packages are that osm2pgsql and libosmium are quite old; as per https://switch2osm.org/serving-tiles/updating-as-people-edit-osm2pgsql-replication/ you'll probably want osm2pgsql 1.4.2 or above.

**Comment by it-solutions-zehaczek** [comment]
Thanks. I will try a selfbuild. I also built osm2pgsql myself.
