### ISSUE TITLE
Figure out maintainer situation

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/mod_tile#214]
mod_tile has not had an active maintainer in a few years. We have 31 PRs open. 

@xamanu has been contributing PRs and has experience with Debian. Would they make a good maintainer? Are they interested?

**Comment by xamanu** [comment]
@pnorman I'm currently packaging `libapache2-mod-tile`, `renderd` and `renderd-example-map` for Debian. I want them to be available to everyone and to be able to operate them responsibly in production. Therefore I am definitely interested in going through [the PRs and suggesting a next version](https://pads.ccc.de/KLhqszpbWM).

I could take on the role of a "gatekeeper" and make sure that everything gets commited in order and is tested. As long as the maintenance is all about handling the contributions, that's fine. Don't expect active development from my side.

So far the feedback from Debian is positive and we it is coming along, but they clearly expressed that we need some activeness in accepting PRs here in order to get the packages accepted.

**Comment by pnorman** [comment]
> I could take on the role of a "gatekeeper" and make sure that everything gets commited in order and is tested. As long as the maintenance is all about handling the contributions, that's fine. Don't expect active development from my side.

Yes, no one is expecting new features from mod_tile or renderd.

**Comment by julienfastre** [comment]
>Yes, no one is expecting new features from mod_tile or renderd

Thanks for all the work you do, @pnorman 

I would like to clarify the situation: why should we not expect new features from renderd/mod_tile ? We are quite concerned with mod_tile, which we use in some project without any new code or bugfixe.

Meanwhile, I am happy to read that some interesting PR here will be merge.

**Comment by xamanu** [comment]
@pnorman what could be the next step here?

**Comment by rory** [comment]
My day job involves installing lots of tile servers, so I would *love* if it was much easier to install `mod_tile` out of the box, so I would love if there was a proper maintainer. I've been talking to @xamanu recently, and they seem very skilled & eager to improve this situation. So that's a +1 from me.

> why should we not expect new features from renderd/mod_tile ?

Although I am relatively happy with the state of `mod_tile` now (though #194 would probably reduce my log spam, and I still forget about #210), I would not be opposed to new features (I have half-attempted to add some [http2 features](https://github.com/rory/mod_tile/tree/http2-server-push)). However, we must remember that being able to develop an apache module is different from a maintainer role, which involves packaging, merging PRs, and all that.

I am not aware right now of someone who is both able to develop new features for `mod_tile` _and_ willing & able to do all the maintainer tasks. To me, the choice now is between “the poor status quo” and “@xamanu doing just the maintainer role”. I believe @xamanu is open to new features. So I don't think anyone is suggesting a permanent feature freeze! 🙂

**Comment by xamanu** [comment]
@jburgess777 and @apmon, may I ask for your perspective on this issue? Thank you! :heart:

**Comment by lonvia** [comment]
@jburgess777 , @apmon Just in case you are not aware, you are currently the official maintainers of mod_tile, i.e. the ones with the power to make somebody else maintainer.

**Comment by jburgess777** [comment]
I have invited @xamanu to be a maintainer of the repo.

I merged a couple of the pending PRs. Sorry for being slow, I don't get much time to work on side projects recently.

**Comment by xamanu** [comment]
Thanks a lot, @jburgess777, for merging and the invitation.
