### ISSUE TITLE
Official instruction mentions outdated fork in the installation procedure

### ISSUE THREAD

**Issue by tajchert** [openstreetmap/mod_tile#234]
Hi,
Official instruction ["Manually building a tile server"](https://switch2osm.org/serving-tiles/manually-building-a-tile-server-20-04-lts/) mentions outdated fork of [SomeoneElseOSM/mod_tile](https://github.com/SomeoneElseOSM/mod_tile/) instead of this repo. 
Is this still needed to used that fork? As it is mentioned in #233  it should work well on its own on Ubuntu 20.04 LTS. I'm not sure if this is the best place to place that issue.
If there is a reason for using this fork it would be great to have ex. link to github issue to follow on progress [as other wise it raises some questions for other projects](https://github.com/Overv/openstreetmap-tile-server/issues/172).

**Comment by SomeoneElseOSM** [comment]
Firstly, I suspect that's a question better asked at https://github.com/switch2osm/switch2osm.github.io/issues rather than here.  However:

Essentially there were two reasons that I created https://github.com/SomeoneElseOSM/mod_tile/ (which predated https://github.com/switch2osm/switch2osm.github.io/ by some time) in the first place.  

- One was that some foibles of mod_tile as it existed then basically wasn't usable at all without some fix-up.  That was resolved once this repository started being maintained again.

- The second was that the "out of the box" scripts for mod_tile still required changing for use outside of osm.org.  That's changing too - you'll notice that https://switch2osm.org/serving-tiles/manually-building-a-tile-server-debian-11/ uses as much as it can from the distribution itself, and the improvements to the Debian packaging means that that guide is much shorter than the others.  I'd expect that the next LTS version of Ubuntu that's based on Debian 11 to be closer to the Debian guide too, and not need a separate "switch2osm" version of mod_tile.  Some "odds and sods" scripts will still be needed though, unless they are added here.

As for the "questions for other projects" I'll address that over at https://github.com/Overv/openstreetmap-tile-server/issues/172 rather than here.

**Comment by tajchert** [comment]
Thanks @SomeoneElseOSM , also thanks for fork that allowed to speed up usage of mod_tile outside of OSM.
I believe this issue either should be closed as of now there is no way to switch to official mod_tile. This issue might be opened once mod_tile is self-sufficient.

**Comment by xamanu** [comment]
Just for your information, the packages are going to be part of the next [Ubuntu release "Hirsute Hippo"](https://packages.ubuntu.com/source/hirsute/libapache2-mod-tile) and future versions.

@SomeoneElseOSM, it would be great to get the script improvements filed up as Pull Requests, so they can become part of the packages and provided together with them. Would be happy to support this, if I could be of help.
