### ISSUE TITLE
`ModTileMissingRequestTimeout 0` doesn't mean infinity

### ISSUE THREAD

**Issue by kenfehling** [openstreetmap/mod_tile#237]
Using the setting `ModTileMissingRequestTimeout 0` it seems to give up right away. To get an "infinite" timeout I have to just set it to some really high number. Should zero mean infinity here?

**Comment by stephankn** [comment]
We are speaking about web requests. If a files is not there, you need a way to tell a timeout after which this is reported.

This setting is exactly doing this: It sets a timeout of Requests of missing tiles. You probably want to handle this client side in a specific way to not block on loading forever. 0 is the lowest timeout possible. If a file is not there, it reports this back immediately.

Infinity might be tricky, as I am not certain that servers will send keep-alives to keep up TCP. And at least tirex has by default a 10 minutes timeout for a render request as well.

**Comment by kenfehling** [comment]
Oh, I see, thanks for your response. I think I had a few misconceptions about this.

I've seen many tutorials containing:
```
ModTileRequestTimeout 0
ModTileMissingRequestTimeout 30
```
so I assumed ```ModTileRequestTimeout 0``` meant wait forever and that ```ModTileMissingRequestTimeout 0``` was showing a different behavior.

With something like this however:
```
ModTileRequestTimeout 86400
ModTileMissingRequestTimeout 30
```
I still get some `HTTP Error 404: Not Found` errors for tiles that actually do produce when given enough time, but with:
```
ModTileRequestTimeout 0
ModTileMissingRequestTimeout 86400
```
it takes all the time it needs and never complains.

**Comment by stephankn** [comment]
You have two different scenarios to consider.

Scenario 1: you have on disk a cached rendered tile, but it is outdated and due to be rendered.
Scenario 2: you have a request for a tile which does not exist.

The option `ModTileRequestTimeout` deals with scenario 1. It controls how long mod_tile waits for the renderer until it gives up and serves the old cached copy.
For interactive maps typically you do not want the client to wait, so you tell mod_tile to return the old cached copy and do re-render the tile in the background. Mod_tile sends tile-requests along with a priority, so renderer can distinguish.
A typical setup is then  `ModTileRequestTimeout 0`.

In scenario 2, there is no cached copy available. Options are either to wait or to return a 404. The option `ModTileMissingRequestTimeout` controls this waiting time.

So in your first test it would wait 30 seconds for the renderer and then give up and return 404, as there is no alternative.
In your other test it returns immediately the tile from disk. Regardless whether it current or not (triggering a rendering in background if needed). For tiles not existing it would wait a very long time. Unless you have other timeouts happening, it would wait for the tile until it is rendered. 

To give some ball-park numbers: The osm-cartho style has roughly these rendering times on a i7-8700:

        style     zoom |      0       1       2       3       4       5       6       7       8       9      10      11      12      13      14      15      16      17      18      19      20
        ---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
        osm            |                                                   12.5s   14.3s   10.9s   10.1s   34.4s   16.3s    8.3s    3.9s   20.6s   21.0s   23.7s   24.7s   22.2s   17.3s   20.5s

**Comment by kenfehling** [comment]
Thank you very much for the explanation, it helps a lot!
