### ISSUE TITLE
Allow the `/dirty`/`/status` URLs to be disabled (& disable them by default)

### ISSUE THREAD

**Issue by amandasaurus** [openstreetmap/mod_tile#272]
Currently `mod_tile` always allows the `/dirty` & `/status` URLs for all tiles. In all servers I set up, I block that with an apache rewrite rule. I suggest improving `mod_tile` by:

(i) The user should be able to turn this option on or off in the apache config (this should be uncontroversial, since it just add 2 `On`/`Off` settings (e.g. `ModTileDirtyUrl Off`)
(ii) I think both settings should be `Off` by default.

I'm possibly able to work on code for this. Does anyone have any issues with my suggestion?

**Comment by xamanu** [comment]
Sounds like a good improvement to me to make this setting explicit as suggested by you.

**Comment by pierzen** [comment]
It seems that the controlable option has been implemented since last week as I cannot dirty tiles anymore 
(example https://tile.openstreetmap.org/10/323/318.png/dirty) where I receive a bad request message with __Error: Could not establish connection. Receiving end does not exist.__.  

Does dirty of tiles under zoom 12 si adding excessive requests ?  Are they other ways for an OSM contributor to dirty tiles ?

**Comment by pnorman** [comment]
No, the PR is still unmerged.

Dirty was [disabled on the CDN](https://github.com/openstreetmap/operations/issues/681) because it doesn't do what people expect, but that's unrelated to mod_tile as it's deployment specific.
