### ISSUE TITLE
conf files do not exist for in Ubuntu 20.04 compilation instructions

### ISSUE THREAD

**Issue by Avatrin** [openstreetmap/mod_tile#295]
I have been following the compilation instructions relatively successfully until it asks me to add two configurations:
sudo cp "etc/apache2/renderd.conf" /etc/apach2/conf.d/renderd.conf
sudo cp "etc/apache2/renderd-example-map.conf" \
  /etc/apache2/conf-enabled/renderd-example-map.conf
  
  These don't exist. While renderd.conf can be found under a different folder, I cannot find any file called renderd-example-map.conf.

**Comment by SomeoneElseOSM** [comment]
https://github.com/openstreetmap/mod_tile/blob/master/etc/apache2/renderd-example-map.conf seems to be a thing?

I'm not sure how (or why?) it differs from the renderd.conf that you'll get if you install in the normal way (i.e. not building from source), other than the references to "cache.tile.openstreetmap.org", which I'd be surprised if you'd want in a deployed version.

**Comment by amandasaurus** [comment]
I have encounted this bug too. the [instructions](https://github.com/openstreetmap/mod_tile/blob/d8a0f29cfe0b8ae15db4e3d3ccf3981366e3bcbf/docs/build/building_on_ubuntu_20_04.md?plain=1#L45) say `sudo cp "etc/apache2/renderd.conf" /etc/apach2/conf.d/renderd.conf`

I think it was removed by @xamanu in 43beadaf0849dfb85e9d2e9ecbab9f6510f6200c

**Comment by hummeltech** [comment]
Closing this issue
- `etc/apache2/renderd.conf` was removed in [43beadaf0849dfb85e9d2e9ecbab9f6510f6200c](https://github.com/openstreetmap/mod_tile/commit/43beadaf0849dfb85e9d2e9ecbab9f6510f6200c#diff-8f99a842d0c72315500ba0db7aa3237667414397e155b5ac1db22300c2f9b7bb)
  - The documentation was updated in #320
- [`etc/apache2/renderd-example-map.conf`](https://github.com/openstreetmap/mod_tile/commits/master/etc/apache2/renderd-example-map.conf) has existed in the current location since `Jul 29, 2021`
