### ISSUE TITLE
render_list just sitting idle

### ISSUE THREAD

**Issue by miqueet** [openstreetmap/mod_tile#426]
when i run render list i seems to not actually do anything and it just appears to be idle. Am I doing something wrong? I have everything setup according to the OSM guide.

```
sudo render_list -m ajt -z 0 -Z 12 -n 4 -l 20 --all
Rendering client
Starting 4 rendering threads
Rendering all tiles from zoom 0 to zoom 12
Rendering all tiles for zoom 0 from (0, 0) to (0, 0)
Rendering all tiles for zoom 1 from (0, 0) to (1, 1)
Rendering all tiles for zoom 2 from (0, 0) to (3, 3)
Rendering all tiles for zoom 3 from (0, 0) to (7, 7)
Rendering all tiles for zoom 4 from (0, 0) to (15, 15)
Rendering all tiles for zoom 5 from (0, 0) to (31, 31)
Rendering all tiles for zoom 6 from (0, 0) to (63, 63)
```
after attaching an strace it does appear my suspicions and it is idle.

sudo strace -p 2675063
strace: Process 2675063 attached
futex(0x55a21e69a308, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, NULL, FUTEX_BITSET_MATCH_ANY

Any advice would be helpful.

**Comment by SomeoneElseOSM** [comment]
>  I have everything setup according to the OSM guide.

Can you link to what instructions you're following? I'm guessing that they might be quite old... What OS are you trying to use "render_list" on?  Depending on what you're actually doing, that "render_list" command line could be wrong in one of several different ways, but you're going to need to provide a bit more information so that people can tell which.

**Comment by miqueet** [comment]
> > I have everything setup according to the OSM guide.
> 
> Can you link to what instructions you're following? I'm guessing that they might be quite old... What OS are you trying to use "render_list" on? Depending on what you're actually doing, that "render_list" command line could be wrong in one of several different ways, but you're going to need to provide a bit more information so that people can tell which.

i am running on ubuntu 22

this is the guide i used to start the server.

https://switch2osm.org/serving-tiles/manually-building-a-tile-server-ubuntu-22-04-lts/

**Comment by hummeltech** [comment]
The documentation you linked to has a map layer named `s2o`, not `ajt`, try using that instead.

E.g.:
```shell
sudo render_list --map=s2o --min-zoom=0 --max-zoom=12 --num-threads=4 --max-load=20 --all
```

**Comment by miqueet** [comment]
ive also noticed that the rendering seems to regenerate after 3 days. Is there something that this guide does not cover that generates the planet-import-complete file?

i see where the 3 days comes from but i would like to not regenerate tiles that frequently.

https://github.com/openstreetmap/mod_tile/blob/master/includes/render_config.h#L82

**Comment by hummeltech** [comment]
Yes, it will use 3 days if you don't have a `PLANET_TIMESTAMP` file:
https://github.com/openstreetmap/mod_tile/blob/9834df0e38a6cd55e06dec8608a64077d32f819a/src/store_file.c#L58-L61
Which is called from and sets the `expired` attribute here:
https://github.com/openstreetmap/mod_tile/blob/9834df0e38a6cd55e06dec8608a64077d32f819a/src/store_file.c#L192-L196

The solution is to generate a `PLANET_TIMESTAMP` file which I believe should be saved to this path on your system:
`/var/cache/renderd/tiles/s2o/planet-import-complete`

All that matters is the `mtime` of the `PLANET_TIMESTAMP` file, so you can `touch -m` it with the `--date` of your last planet import (or you can `touch -m` it with a `--date`/`-t in the past so that it will not come up as `expired`.)

**Comment by hummeltech** [comment]
You can see how `tile.openstreetmap.org` does it here:
https://github.com/openstreetmap/chef/blob/237d93489bca6fbae88dd2a9f63fedca0aba0a36/cookbooks/tile/templates/default/update-lowzoom.erb#L27-L30

**Comment by miqueet** [comment]
> You can see how `tile.openstreetmap.org` does it here: https://github.com/openstreetmap/chef/blob/237d93489bca6fbae88dd2a9f63fedca0aba0a36/cookbooks/tile/templates/default/update-lowzoom.erb#L27-L30

I figured it may be as easy as a touch but thank you for confirming.
