### ISSUE TITLE
mapnik-config parameters don't work with 2.0

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/mod_tile#84]
d0dab6e8ff20f089b509e8772f67e3352b019bc5 (#83) introduced getting Mapnik's dependencies with `$MAPNIK_CONFIG --dep-includes`. The problem is, this doesn't seem to exist with Mapnik 2.0, where this output is generated in the Makefile

``` make
MAPNIK_CFLAGS = -I/usr/local/include -I/usr/local/include -I/usr/include -I/usr/include/freetype2 -I/usr/include/libxml2 -I/usr/include/gdal -I/usr/include/postgresql -DHAVE_JPEG -DBOOST_REGEX_HAS_ICU -ansi -Wall -pthread -ftemplate-depth-300 -DLINUX -DBOOST_SPIRIT_THREADSAFE -DMAPNIK_THREADSAFE -O3 -finline-functions -Wno-inline -DNDEBUG -DLIBTOOL_SUPPORTS_ADVISE -DHAVE_LIBXML2
MAPNIK_CONFIG = /usr/local/bin/mapnik-config
MAPNIK_INCLUDES =  Usage: mapnik-config [OPTION]

Known values for OPTION are:

  --prefix          display mapnik prefix [default /usr/local]
  --prefix=DIR      change mapnik prefix [default /usr/local]
  --libs            print library linking information
  --dep-libs        print library linking information for mapnik depedencies
  --ldflags         print library paths (-L) information
  --cflags          print pre-processor and compiler flags
  --fonts           print default fonts directory
  --input-plugins   print default input plugins directory
  --json            print all config options as json object
  --help            display this help and exit
  -v --version      output version information
  --git-revision    output git hash
MAPNIK_LDFLAGS = -L/usr/local/lib -lmapnik
MAPNIK_VERSION = 2.0.3-pre
```

Reported via IRC for someone following switch2osm with Ubuntu 12.04.

**Comment by markmcdonald51** [comment]
So is this fixed in some other branch? I am trying to compile this in as well and of course having the same problem. eg:

mark@Ubuntu-1404-trusty-64-minimal:~/src/mod_tile$ make
Makefile:445: *** missing separator.  Stop.


the output from the command mentioned above produces the lines below... but where do I put this? in the Makefile??.. Any help is totally appreciated. Thanks!

:~/src/mod_tile$ mapnik-config --json
{ "prefix": "/usr/local", "mapnik_libname": "mapnik", "mapnik_include": "/usr/local/include", "mapnik_lib": "/usr/local/lib", "version": "2.0.3-pre", "ldflags": " -L/usr/local/lib -L/usr/lib -L/usr/lib/x86_64-linux-gnu", "dep_libs": " -lfreetype -lltdl -lpng -ltiff -lz -lproj -licuuc -lboost_filesystem -lboost_regex -ljpeg -lxml2 -lboost_thread -lboost_system", "other_includes": " -I/usr/local/include -I/usr/include -I/usr/include/freetype2 -I/usr/include/libxml2 -I/usr/include/postgresql -DHAVE_JPEG -DBOOST_REGEX_HAS_ICU -ansi -Wall -pthread -ftemplate-depth-300 -DLINUX -DBOOST_SPIRIT_THREADSAFE -DMAPNIK_THREADSAFE -O3 -finline-functions -Wno-inline -DNDEBUG -DLIBTOOL_SUPPORTS_ADVISE -DHAVE_LIBXML2 ", "fonts": "/usr/share/fonts/truetype", "input_plugins": "/usr/local/lib/mapnik/input", "git_revision": "025b04fe2b8f5b25ce2b5b4246422d6c0511234f " }

**Comment by bkboggy** [comment]
I'm having this issue.  Has it been fixed at all?

**Comment by johnsonc** [comment]
Hallo, bumped into this issue right now. Dane had suggested that changes were in another branch. Seems like they haven't been merged?

**Comment by johnsonc** [comment]
Dane's changes work btw. Just tested.

**Comment by progserega** [comment]
I have this issue, and try fix it in patch:
https://github.com/openstreetmap/mod_tile/issues/100

**Comment by xamanu** [comment]
Recent versions of `mod_tile` target mapnik 3.0 or later. Closing here.
